//Uncomment this line on creating a translation file
import { editorLocalization, defaultStrings } from "../editorLocalization";

export var japaneseStrings = {
  //survey templates
  survey: {
    edit: "編集",
    dropQuestion: "ツールボックスから質問に使うアイテムをドロップしてください。",
    copy: "Copy",
    addToToolbox: "ツールボックスに追加",
    deletePanel: "パネル削除",
    deleteQuestion: "質問削除",
    convertTo: "Convert to",
    drag: "Drag element"
  },
  //questionTypes
  qt: {
    default: "Default",
    checkbox: "チェックボックス",
    comment: "コメント",
    imagepicker: "イメージピッカー",
    dropdown: "ドロップダウン",
    file: "ファイル",
    html: "Html",
    matrix: "Matrix (single choice)",
    matrixdropdown: "Matrix (multiple choice)",
    matrixdynamic: "Matrix (dynamic rows)",
    multipletext: "複数行入力",
    panel: "パネル",
    paneldynamic: "Panel (dynamic panels)",
    radiogroup: "ラジオグループ",
    rating: "評価",
    text: "1行入力",
    boolean: "ブール値",
    expression: "自由表現"
  },
  //Strings in Editor
  ed: {
    defaultLocale: "Default ({0})",
    survey: "アンケート",
    settings: "アンケート設定",
    editSurvey: "アンケート編集",
    addNewPage: "ページ追加",
    moveRight: "右にスクロール",
    moveLeft: "左にスクロール",
    deletePage: "ページ削除",
    editPage: "ページ編集",
    edit: "編集",
    newPageName: "ページ",
    newQuestionName: "質問",
    newPanelName: "パネル",
    testSurvey: "アンケートテスト",
    testSurveyAgain: "もう一度テストアンケートを実施する",
    testSurveyWidth: "Survey width: ",
    embedSurvey: "Embed Survey",
    translation: "Translation",
    saveSurvey: "アンケートを保存",
    designer: "アンケートデザイナ",
    jsonEditor: "JSONエディタ",
    undo: "元に戻す",
    redo: "やり直す",
    options: "オプション",
    generateValidJSON: "Generate Valid JSON",
    generateReadableJSON: "Generate Readable JSON",
    toolbox: "ツールボックス",
    toolboxGeneralCategory: "General",
    delSelObject: "Delete selected object",
    editSelObject: "Edit selected object",
    correctJSON: "Please correct JSON.",
    surveyResults: "Survey Result: ",
    modified: "Modified",
    saving: "Saving",
    saved: "Saved",
    saveError: "Error! Editor content is not saved.",
    translationAddLanguage: "Select language to translate",
    translationShowAllStrings: "Show all strings",
    translationShowAllPages: "Show all pages",
    translationNoStrings: "No strings to translate. Please, change the filter.",
    translationExportToSCVButton: "Export to CSV",
    translationImportFromSCVButton: "Import from CSV"
  },
  //Property names in table headers
  pel: {
    isRequired: "Required?"
  },
  //Property Editors
  pe: {
    apply: "適用",
    ok: "OK",
    cancel: "キャンセル",
    reset: "リセット",
    close: "Close",
    delete: "削除",
    addNew: "新規追加",
    addItem: "クリックしてアイテムを追加...",
    removeAll: "全て削除",
    edit: "編集",
    itemValueEdit: "Visible If",
    editChoices: "選択肢の編集",
    move: "移動",
    empty: "<empty>",
    notEmpty: "<edit value>",
    fastEntry: "クイック入力",
    formEntry: "フォーム入力",
    testService: "Test the service",
    conditionSelectQuestion: "質問を選択...",
    conditionValueQuestionTitle: "値を入力/選択してください",
    conditionButtonAdd: "Add",
    conditionButtonReplace: "Replace",
    conditionHelp:
      "Please enter a boolean expression. It should return true to keep the question/page visible. For example: {question1} = 'value1' or ({question2} * {question4}  > 20 and {question3} < 5)",
    expressionHelp:
      "Please enter an expression. You may use curly brackets to get access to the question values: '{question1} + {question2}', '({price}*{quantity}) * (100 - {discount})'",
    aceEditorHelp: "Press ctrl+space to get expression completion hint",
    aceEditorRowTitle: "Current row",
    aceEditorPanelTitle: "Current panel",
    showMore: "For more details please check the documentation",
    conditionShowMoreUrl:
      "https://surveyjs.io/Documentation/LibraryParameter?id=QuestionBase&parameter=visibleIf",
    assistantTitle: "Available questions:",
    cellsEmptyRowsColumns: "There is should be at least one column or row",

    propertyIsEmpty: "Please enter a value",
    value: "Value",
    text: "Text",
    rowid: "Row ID",
    imageLink: "Image Link",
    columnEdit: "Edit column: {0}",
    itemEdit: "Edit item: {0}",

    url: "URL",
    path: "Path",
    valueName: "Value name",
    titleName: "Title name",

    hasOther: "Has other item",
    otherText: "Other item text",
    name: "名称",
    title: "タイトル",
    cellType: "Cell type",
    colCount: "Column count",
    choicesOrder: "Select choices order",
    visible: "表示？",
    isRequired: "必須項目？",
    startWithNewLine: "Is start with new line?",
    rows: "Row count",
    placeHolder: "Input place holder",
    showPreview: "Is image preview shown?",
    storeDataAsText: "Store file content in JSON result as text",
    maxSize: "Maximum file size in bytes",
    imageHeight: "Image height",
    imageWidth: "Image width",
    rowCount: "Row count",
    columnLayout: "Columns layout",
    addRowLocation: "Add row button location",
    addRowText: "Add row button text",
    removeRowText: "Remove row button text",
    minRateDescription: "Minimum rate description",
    maxRateDescription: "Maximum rate description",
    inputType: "Input type",
    optionsCaption: "オプションの見出し",
    defaultValue: "Default value",
    cellsDefaultRow: "Default cells texts",

    surveyEditorTitle: "アンケート設定の編集",
    qEditorTitle: "編集: {0}",

    maxLength: "Maximum length",

    //survey
    showTitle: "タイトル 表示/非表示",
    locale: "初期設定言語",
    mode: "モード (編集/読取専用)",
    clearInvisibleValues: "非表示の値をクリア",
    cookieName: "Cookie名 (無効にするためにはアンケートをローカルで2回実行)",
    sendResultOnPageNext: "次ページ遷移時に結果を送信",
    storeOthersAsComment: "'その他'の値を別フィールドに保持",
    showPageTitles: "ページタイトルの表示",
    showPageNumbers: "ページ番号の表示",
    pagePrevText: "[前ページ]ボタンの文字",
    pageNextText: "[次ページ]ボタンの文字",
    completeText: "[完了]ボタンの文字",
    startSurveyText: "[スタート]ボタンの文字",
    showNavigationButtons: "ナビゲーションボタンの表示 (初期ナビゲーション)",
    showPrevButton: "[前ページ]ボタンの表示 (前のページに戻ることがあります)",
    firstPageIsStarted: "最初のページは開始ページとする",
    showCompletedPage: "完了ページの表示(completedHtml)",
    goNextPageAutomatic:
      "全ての質問に回答したとき、自動的に次ページに遷移する",
    showProgressBar: "プログレスバーの表示",
    questionTitleLocation: "質問タイトル位置",
    requiredText: "必須入力を示す文字",
    questionStartIndex: "質問のインデックス (1, 2 or 'A', 'a')",
    showQuestionNumbers: "質問番号の表示",
    questionTitleTemplate:
      "質問タイトルのテンプレート、初期は: '{no}. {require} {title}'",
    questionErrorLocation: "質問エラー表示の位置",
    focusFirstQuestionAutomatic: "ページ移動時に、最初の質問にフォーカスする",
    questionsOrder: "ページ上のエレメント順",
    maxTimeToFinish: "アンケート終了までの時間",
    maxTimeToFinishPage: "ページ終了までの時間",
    showTimerPanel: "タイマーパネル表示",
    showTimerPanelMode: "タイマーパネル表示モード",
    renderMode: "Render mode",
    allowAddPanel: "Allow adding a panel",
    allowRemovePanel: "Allow removing the panel",
    panelAddText: "Adding panel text",
    panelRemoveText: "Removing panel text",
    isSinglePage: "全てのエレメントを1ページに表示",

    tabs: {
      general: "一般",
      fileOptions: "オプション",
      html: "Htmlエディタ",
      columns: "列",
      rows: "行",
      choices: "選択肢",
      items: "アイテム",
      visibleIf: "Visible If",
      enableIf: "Enable If",
      rateValues: "Rate Values",
      choicesByUrl: "Choices from Web",
      matrixChoices: "Default Choices",
      multipleTextItems: "Text Inputs",
      validators: "入力検証",
      navigation: "ナビゲーション",
      question: "質問",
      completedHtml: "完了時のHtml",
      loadingHtml: "ローディング時のHtml",
      timer: "タイマー/クイズ",
      triggers: "トリガー",
      templateTitle: "テンプレートタイトル"
    },
    editProperty: "プロパティ編集 '{0}'",
    items: "[ Items: {0} ]",

    enterNewValue: "Please, enter the value.",
    noquestions: "アンケートに質問がひとつもありません。",
    createtrigger: "トリガーを作成してください。",
    triggerOn: "On ",
    triggerMakePagesVisible: "Make pages visible:",
    triggerMakeQuestionsVisible: "Make elements visible:",
    triggerCompleteText: "Complete the survey if succeed.",
    triggerNotSet: "The trigger is not set",
    triggerRunIf: "Run if",
    triggerSetToName: "Change value of: ",
    triggerFromName: "Copy value from: ",
    triggerRunExpression: "Run this Expression:",
    triggerSetValue: "to: ",
    triggerIsVariable: "Do not put the variable into the survey result."
  },
  //Property values
  pv: {
    true: "真",
    false: "偽",
    inherit: "inherit",
    show: "show",
    hide: "hide",
    default: "default",
    initial: "initial",
    random: "random",
    collapsed: "collapsed",
    expanded: "expanded",
    none: "none",
    asc: "ascending",
    desc: "descending",
    indeterminate: "indeterminate",
    decimal: "decimal",
    currency: "currency",
    percent: "percent",
    firstExpanded: "firstExpanded",
    off: "off",
    onPanel: "onPanel",
    onSurvey: "onSurvey",
    list: "list",
    progressTop: "progressTop",
    progressBottom: "progressBottom",
    progressTopBottom: "progressTopBottom",
    horizontal: "horizontal",
    vertical: "vertical",
    top: "top",
    bottom: "bottom",
    topBottom: "top and bottom",
    left: "left",
    color: "color",
    date: "date",
    datetime: "datetime",
    "datetime-local": "datetime-local",
    email: "email",
    month: "month",
    number: "number",
    password: "password",
    range: "range",
    tel: "tel",
    text: "text",
    time: "time",
    url: "url",
    week: "week",
    hidden: "hidden",
    on: "on",
    onPage: "onPage",
    edit: "edit",
    display: "display",
    onComplete: "onComplete",
    onHidden: "onHidden",
    all: "all",
    page: "page",
    survey: "survey",
    onNextPage: "onNextPage",
    onValueChanged: "onValueChanged"
  },
  //Operators
  op: {
    empty: "is empty",
    notempty: "is not empty",
    equal: "equals",
    notequal: "not equals",
    contains: "contains",
    notcontains: "not contains",
    greater: "greater",
    less: "less",
    greaterorequal: "greater or equals",
    lessorequal: "less or equals"
  },
  //Embed window
  ew: {
    angular: "Use Angular version",
    jquery: "Use jQuery version",
    knockout: "Use Knockout version",
    react: "Use React version",
    vue: "Use Vue version",
    bootstrap: "For bootstrap framework",
    standard: "No bootstrap",
    showOnPage: "Show survey on a page",
    showInWindow: "Show survey in a window",
    loadFromServer: "Load Survey JSON from server",
    titleScript: "Scripts and styles",
    titleHtml: "HTML",
    titleJavaScript: "JavaScript"
  },
  //Test Survey
  ts: {
    selectPage: "テストするページを選択"
  },
  validators: {
    answercountvalidator: "answer count",
    emailvalidator: "e-mail",
    expressionvalidator: "expression",
    numericvalidator: "numeric",
    regexvalidator: "regex",
    textvalidator: "text"
  },
  triggers: {
    completetrigger: "complete survey",
    setvaluetrigger: "set value",
    copyvaluetrigger: "copy value",
    runexpressiontrigger: "run expression",
    visibletrigger: "change visibility"
  },
  //Properties
  p: {
    name: "名称",
    title: {
      name: "タイトル",
      title: "Leave it empty, if it is the same as 'Name'"
    },

    navigationButtonsVisibility: "ナビゲーションの表示",
    questionsOrder: "質問順",
    maxTimeToFinish: "終了までの時間",

    visible: "表示",
    visibleIf: "表示条件",
    questionTitleLocation: "質問タイトル位置",
    description: "説明",
    state: "state",
    isRequired: "入力必須？",
    indent: "インデント",
    requiredErrorText: "必須未入力エラー時のテキスト",
    startWithNewLine: "改行して開始",
    innerIndent: "innerIndent",
    page: "ページ",

    width: "幅",

    commentText: "コメント",
    valueName: "値名称",
    enableIf: "有効化の条件",
    defaultValue: "初期値",
    correctAnswer: "正解",
    readOnly: "読取専用",
    validators: "入力検証",
    titleLocation: "タイトル位置",

    hasComment: "コメント欄の表示",
    hasOther: "その他",
    choices: "選択肢",
    choicesOrder: "選択肢並び順",
    choicesByUrl: "URLから選択肢設定",
    otherText: "[その他]の文字",
    otherErrorText: "[その他]の文字エラーテキスト",
    storeOthersAsComment: "'その他'の値を別フィールドに保持",

    label: "ラベル",
    showTitle: "タイトル表示",
    valueTrue: "valueTrue",
    valueFalse: "valueFalse",

    cols: "cols",
    rows: "rows",
    placeHolder: "プレースホルダー",

    optionsCaption: "オプションの見出",

    expression: "expression",
    format: "format",
    displayStyle: "displayStyle",
    currency: "currency",
    useGrouping: "useGrouping",

    showPreview: "showPreview",
    allowMultiple: "allowMultiple",
    imageHeight: "imageHeight",
    imageWidth: "imageWidth",
    storeDataAsText: "storeDataAsText",
    maxSize: "maxSize",

    html: "html",

    columns: "columns",
    cells: "cells",
    isAllRowRequired: "isAllRowRequired",

    horizontalScroll: "horizontalScroll",
    cellType: "cellType",
    columnsLayout: "columnsLayout",
    columnColCount: "columnColCount",
    columnMinWidth: "columnMinWidth",

    rowCount: "rowCount",
    minRowCount: "minRowCount",
    maxRowCount: "maxRowCount",
    keyName: "keyName",
    keyDuplicationError: "keyDuplicationError",
    confirmDelete: "confirmDelete",
    confirmDeleteText: "confirmDeleteText",
    addRowLocation: "addRowLocation",
    addRowText: "addRowText",
    removeRowText: "removeRowText",

    items: "items",
    itemSize: "itemSize",
    colCount: "列数",

    templateTitle: "templateTitle",
    templateDescription: "templateDescription",
    allowAddPanel: "allowAddPanel",
    allowRemovePanel: "allowRemovePanel",
    panelCount: "panelCount",
    minPanelCount: "minPanelCount",
    maxPanelCount: "maxPanelCount",
    panelsState: "panelsState",
    panelAddText: "panelAddText",
    panelRemoveText: "panelRemoveText",
    panelPrevText: "panelPrevText",
    panelNextText: "panelNextText",
    showQuestionNumbers: "質問番号の表示",
    showRangeInProgress: "showRangeInProgress",
    renderMode: "renderMode",
    templateTitleLocation: "templateTitleLocation",

    rateValues: "rateValues",
    rateMin: "rateMin",
    rateMax: "rateMax",
    rateStep: "rateStep",
    minRateDescription: "minRateDescription",
    maxRateDescription: "maxRateDescription",

    inputType: "入力タイプ",
    size: "size",

    locale: "ロケール",
    focusFirstQuestionAutomatic: "先頭の質問にフォーカス",
    completedHtml: "完了時のHtml",
    completedBeforeHtml: "完了前のHtml",
    loadingHtml: "ローディング時のHtml",
    triggers: "トリガー",
    cookieName: "cookie名",
    sendResultOnPageNext: "次ページ遷移時に結果を送信",
    showNavigationButtons: "ナビゲーションボタンの表示",
    showPrevButton: "[前ページ]ボタンの表示",
    showPageTitles: "ページタイトルの表示",
    showCompletedPage: "完了ページの表示",
    showPageNumbers: "ページ番号の表示",
    questionErrorLocation: "質問エラー表示の位置",
    showProgressBar: "プログレスバーの表示",
    mode: "モード",
    goNextPageAutomatic: "自動で次ページに遷移",
    checkErrorsMode: "エラーチェックモード",
    clearInvisibleValues: "非表示文字のクリア",
    startSurveyText: "アンケート開始ボタンの文字",
    pagePrevText: "[前ページ]ボタンの文字",
    pageNextText: "[次ページ]ボタンの文字",
    completeText: "完了時のテキスト",
    requiredText: "必須入力を示す文字",
    questionStartIndex: "質問のインデックス",
    questionTitleTemplate: "質問タイトルのテンプレート",
    firstPageIsStarted: "最初のページを開始ページ",
    isSinglePage: "シングルページ",
    maxTimeToFinishPage: "ページ終了までの時間",
    showTimerPanel: "タイマーパネル表示",
    showTimerPanelMode: "タイマーパネル表示モード",

    defaultPanelValue: "defaultPanelValue",
    defaultRowValue: "defaultRowValue",
    hasNone: "選択なし",
    noneText: "[選択なし]の文字",

    text: "text",
    minValue: "minimum value",
    maxValue: "maximum value",
    minLength: "最小文字列長",
    maxLength: "最大文字列長",
    allowDigits: "allow digits",
    minCount: "minumum count",
    maxCount: "maximum count",
    regex: "regular expression"
  }
};
//Uncomment this line on creating a translation file. You should replace "en" and enStrings with your locale ("fr", "de" and so on) and your variable.
editorLocalization.locales["jp"] = japaneseStrings;
